# Generated by Django 5.2.1 on 2025-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logframe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='actual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='baseline',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
