# Generated by Django 5.2.1 on 2025-06-26 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logframe', '0002_indicator_actual_indicator_baseline_indicator_target_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='projects.project'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='projects.project'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='output',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='projects.project'),
        ),
    ]
