# Generated by Django 5.2.1 on 2025-07-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logframe', '0003_goal_project_indicator_project_outcome_project_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='project',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='project',
        ),
        migrations.RemoveField(
            model_name='output',
            name='project',
        ),
        migrations.AlterField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='projects.project'),
            preserve_default=False,
        ),
    ]
