# Generated by Django 5.2.1 on 2025-05-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
