# Generated by Django 5.2.3 on 2025-06-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicatorcategory_remove_indicator_baseline_and_more'),
        ('logframe', '0002_indicator_actual_indicator_baseline_indicator_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='indicatoractivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='indicatorcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Indicator Categories'},
        ),
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'ordering': ['-date_collected']},
        ),
        migrations.AddField(
            model_name='indicator',
            name='actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='baseline',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_set_ind', to='logframe.output'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='indicators.indicatorcategory'),
        ),
        migrations.AlterField(
            model_name='indicatoractivity',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='indicators.indicator'),
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='indicators.indicator'),
        ),
    ]
